name: 'My Personal Website'
description: 'So much potential'
tagline: 'yada yada'
url: 'https://naalu.github.io/SampleWebsiteTemplate/'
baseurl: '/SampleWebsite'
paginate: 10

markdown: kramdown
highlighter: rouge

# Permalinks
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink: pretty
# permalink: /:year/:month/:title/
relative_permalinks: false

# About/contact
author: Karl 'Chris' Reger

# GitHub
github:
  repo: https://github.com/Naalu/SampleWebsiteTemplate

# Feed Stuff
gems:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-seo-tag
